require("vish.config.lazy")
require("vish.config.mason")
require("vish.config.telescope")
require("vish.config.treesitter")
--require("vish.config.null-ls")
require("vish.config.catpucchin")
require("vish.config.lualine")
require("vish.config.cmp")
